---

name: 'Another Action'
description: 'Another example action'

inputs:
  input1:
    description: 'An example input'
    required: true
    default: 'default value'


runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2

    - run: echo ${{ inputs.input1 }}
